NEO-TAT/tat_flutter

pubspec.lock
pubspec.yaml

`firebase_core (0.4.4+3)`  會讓 iOS build 失敗，因此將版本將到 `0.4.4`

[Fix] Modify firebase_core to fix iOS error

---

lib/src/connector/core/DioConnector.dart
lib/src/connector/interceptors/response_cookie_filter.dart

I don't know when it started, the back end of the school added a cookie to the response header, its name style is `BIGipServerVPFl/xxxxxxxxxxxxxxx`, and in this name, there are characters that do not meet the requirements, which will cause dio parsing errors, so it needs to be filtered out .
So, I added a blacklist filter repeater that allows us to filter out these weird cookie names by providing a regexp.

Fix cookie name not in rule from school api response error

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock
lib/generated/l10n.dart
lib/src/file/FileStore.dart
lib/src/util/PermissionsUtil.dart
lib/ui/pages/fileviewer/FileViewerPage.dart
lib/ui/pages/fileviewer/widgets/custom_alert.dart
lib/ui/pages/fileviewer/widgets/dir_item.dart
lib/ui/pages/fileviewer/widgets/dir_popup.dart
lib/ui/pages/fileviewer/widgets/file_icon.dart
lib/ui/pages/fileviewer/widgets/file_item.dart
lib/ui/pages/fileviewer/widgets/file_popup.dart
lib/ui/pages/fileviewer/widgets/path_bar.dart
lib/ui/pages/fileviewer/widgets/sort_sheet.dart
pubspec.lock
pubspec.yaml

- The permission check process for android external storage (id = 15) is wrong and redundant.
In this PR, I just rewrite it again, and it seems works fine on API level 31.
- Issue fixed:
https://stackoverflow.com/questions/51607002/flutter-unable-to-create-directory-os-error-read-only-file-system
- The root file download path has been move to ./TAT now.
- remove path text on the appBar of file page.

Fix: storage permission check wrong

---

lib/src/task/ntut/NTUTTask.dart
lib/ui/other/RouteUtils.dart

In the new `GetX` package, it has a new API when using `Get.to(...)`:
```dart
Get.to(
() => ExamplePage(),
transition: transition,
);
```
instead of
```dart
Get.to(
ExamplePage(),
transition: transition,
);
```

Fix: getx route change warning

---

ios/Podfile.lock
lib/src/connector/adapters/early_interceptor_adapter.dart
lib/src/connector/core/DioConnector.dart
lib/src/task/iplus/IPlusCourseAnnouncementTask.dart
lib/src/task/iplus/IPlusCourseFileTask.dart
lib/ui/pages/password/CheckPasswordDialog.dart
pubspec.lock
pubspec.yaml

The response header `ContentType` from the i-school APIs may has some non-standard values.
for example: `text/html;;`, which contains an illegal `;` after the first `;`.
And this will cause the dio (httpClient) to throw an error, and makes the data parsing steps terminated unexpectedly.
According to #63, we cannot use dio's interceptor to solve this problem, so I create a custom `HttpClientAdapter` and insert it into dio instance to modify the strange header before any interceptors be executed.

Fix: dio istudy header parse error

---

lib/src/connector/NTUTConnector.dart
lib/src/connector/core/Connector.dart
lib/src/task/iplus/IPlusCourseAnnouncementTask.dart
lib/src/task/iplus/IPlusCourseFileTask.dart
lib/ui/pages/other/OtherPage.dart

The avatar on the `OtherPage` will appear a download error since we have updated the `dio` package version.
The reason why it failed is because the `cookieJar` returns a `Future` when calling `loadForRequest` method. (In `getLoginHeaders` function)
So we should wrap the caller side into a `Future` function, and make the avatar Widget be wrapped into a `FutureBuilder`.
1. Open the APP
2. ensure logged in.
3. Go to the `OtherPage` and to see if the avatar is shown.
(If it is not, retry sometimes, because it might be affacted by the school API.)

Fix: profile avatar download error

---

lib/src/connector/core/DioConnector.dart
lib/ui/pages/logconsole/log_console.dart

The debug screen (Dio log & App log) was using some deprecated theme API when the flutter sdk version is `1.22.6`, but now it is `2.10.5`.
So we just enforce them to use light theme, which is a default theme of `ThemeData` to prevent the theme `brightness` not equal errors.
- Go to the debug page and to see if it is normal.

Fix debug page color scheme error

---

lib/src/store/local_storage.dart
lib/src/task/ntut/ntut_task.dart
lib/ui/other/route_utils.dart
lib/ui/pages/coursetable/course_table_page.dart
lib/ui/pages/other/other_page.dart
lib/ui/pages/other/page/about_page.dart
lib/ui/pages/other/page/setting_page.dart
lib/ui/screen/login_screen.dart

The main page is available for users who does not login, this seems very strange.
So in this PR, I've fix this issue, makes
- required user's login to see the main screen.
- when user login failed, immediately redirect to login screen.
- when user click logout, immediately redirect to login screen.
Before start: Uninstall the app, then build a new one to your device.
1. login as a real account, make sure you can login and do everything.
2. logout, to see if the login screen is in front of you.
3. type in a fake account, to see if it has moved back to the login screen and shows an error dialog.
4. In Android, click the `back` button to see if the app is direly closed, not just close the login screen.
5. In iOS, continue the step 3, make sure there's no any back button appears in the login …

Fix content access not correct when not login ntut

---

lib/ui/pages/coursedetail/course_detail_page.dart
lib/ui/pages/coursedetail/screen/course_info_page.dart
lib/ui/pages/coursedetail/tab_page.dart
lib/ui/pages/coursetable/course_table_page.dart

Since #86 , the UI has been migrated to Material 3, but that causes some detailed issues.
- course table page block text overflow
- course info page text overflow
- too ugly(?
So here makes some fix for those places.
- Open ios and aos version's TAT, and go to course table page and course detail page to see if they looks well.
(sorry, I have no time to do that...)

Optimize UI for course pages

---

lib/src/connector/score_connector.dart
lib/src/model/course/course_score_json.dart
lib/ui/pages/coursetable/course_table_page.dart

This problem is caused by school API changed.
The API has moved the score data elements to another index, so it will throw parse error when we perform some double conversions (content is changed to a non-parsable value).
So in this PR, we just adjust the index to fit the new responses.
1. Goto grade page.
2. refresh greade
3. see if the `學業成績` has strange value, such as `0.0`, etc.

Fix some grade info display wrong

---

lib/src/config/app_link.dart
lib/src/version/update/app_update.dart
lib/ui/other/route_utils.dart
lib/ui/pages/coursedetail/screen/course_info_page.dart
lib/ui/pages/other/other_page.dart
lib/ui/pages/other/page/contributors_page.dart
lib/ui/pages/other/page/privacy_policy_page.dart
lib/ui/pages/other/page/sub_system_page.dart
lib/ui/pages/webview/in_app_webview_callbacks.dart
lib/ui/pages/webview/tat_web_view.dart
lib/ui/pages/webview/web_view_button_bar.dart
lib/ui/pages/webview/web_view_page.dart

This PR is aim to solve #127 , and also migrate current IAB code to null-safety version.
- open `資訊系統` in the `OtherPage` and go to `網路狀態` page, see if it shown.
- try other pages in `資訊系統` to see if they works.

Refactor IAB with null-safety migrations

---

android/build.gradle
ios/Podfile.lock
lib/main.dart
lib/src/connector/core/dio_connector.dart
lib/src/controllers/calendar_controller.dart
lib/src/task/iplus/iplus_course_announcement_task.dart
lib/src/task/iplus/iplus_course_file_task.dart
lib/src/task/ntut/ntut_task.dart
lib/src/util/language_util.dart
lib/ui/other/error_dialog.dart
lib/ui/pages/calendar/calendar_page.dart
lib/ui/pages/coursedetail/screen/ischoolplus/iplus_file_page.dart
lib/ui/pages/other/other_page.dart
lib/ui/pages/roll_call_remind/new_roll_call_monitor_card_widget.dart
lib/ui/pages/roll_call_remind/scheduled_roll_call_monitor_card_widget.dart
lib/ui/pages/webview/web_view_page.dart
pubspec.lock
pubspec.yaml

Upgrade all dependencies and flutter sdk version to `3.3.10`.
The Android Kotlin version has upgraded to `1.8.0`.
There are three breaking changes:
- Awsome Dialog
The dependency version has upgraded to v3, which deprecated the origin `DialogTyle` values.
These update changes has addressed here: [3a0d35a](https://github.com/NEO-TAT/tat_flutter/pull/154/commits/3a0d35a6ab76d6dd1b4a526ae9ef97de773bd881).
- Alice
Since the `alice` package on [`pub.dev`](https://pub.dev/packages/alice) depends on lots of its sub-packages which makes us hard to maintain TAT's dependency versions, we have migrated it to the [`alice_lightweight`](https://pub.dev/packages/alice_lightweight) package.
- Table Calendar
Through the `table_calendar` package version has been upgraded to v3, we rebuilt the whole …

Refactor Calendar page & Pump flutter version to 3.3.10

---

lib/generated/intl/messages_en.dart
lib/generated/intl/messages_zh_TW.dart
lib/generated/l10n.dart
lib/l10n/intl_en.arb
lib/l10n/intl_zh_TW.arb
lib/src/config/app_colors.dart
lib/src/config/app_themes.dart
lib/ui/pages/coursedetail/screen/course_info_page.dart
lib/ui/pages/coursetable/course_table_page.dart
lib/ui/pages/score/app_bar_action_buttons.dart
lib/ui/pages/score/course_score_section.dart
lib/ui/pages/score/rank_grade_metrics.dart
lib/ui/pages/score/score_page.dart
lib/ui/pages/score/semester_score_grade_metrics.dart
lib/ui/pages/score/widgets/calculation_warning_widget.dart
lib/ui/pages/score/widgets/grade_metrics_cell_widget.dart
lib/ui/pages/score/widgets/metrics_title_widget.dart
lib/ui/pages/score/widgets/score_tile_widget.dart

This PR tried to refactor the score page (also known as the grade page), which specifically did the following things:
1. The score detail info in each semester has been refined into a 3-part-metric:
- the `course score` section
- the `semester score` section
- the `rank` section
2. The operation in this page, the `refresh` and `calculate credit`, which were originally located in a `PopupMenuButton`, has been redesigned to `IconButton` directly put inside the `AppBar`.
3. Change the divider color of the theme for using the `Divider` widget in somewhere.
1. Go to the score page, refresh, and see if the score in each semester could be showed properly (no any critical UI problems).
2. Go to course table page, check the background looks the same as before.
3. Go to a course detail page, check …

Refactor score page (Only score parts)

---

android/app/src/main/AndroidManifest.xml
lib/src/file/file_download.dart
lib/src/file/file_store.dart
lib/src/repositories/auto_roll_call_schedule_repository_impl.dart
lib/src/util/permissions_util.dart
lib/ui/other/my_toast.dart
lib/ui/pages/coursedetail/screen/ischoolplus/iplus_file_page.dart
lib/ui/screen/main_screen.dart

This PR did these things:
- change the bottomNavigationStyle to fixed (which shows the label)
- Add success & failed dialog to file download process.
- fix illegal firebase access while initializing
- remove unneeded aos permissions.
- TBD

Improve bottom bar and file downloads

---

ios/Runner/Info.plist

Mentioned in #165, the App seems not restricted to only portrait mode since upgraded to flutter 3.7.
Due to the priority decision, we decided to postpone this issue to next version.
So in this PR, we have directly remove all possibility of using landscape mode in App. This also makes user not be able to use the landscape mode in the video page too.   
In iOS, try to rotate device to landscape form, check if the App had changed its orientation type.

chore: hard disable landscape on ios platform

---

android/app/src/main/AndroidManifest.xml
lib/src/config/constants.dart
lib/src/providers/category_provider.dart
lib/src/util/permissions_util.dart
lib/ui/pages/fileviewer/file_viewer_page.dart
lib/ui/pages/fileviewer/widgets/custom_alert.dart
lib/ui/pages/fileviewer/widgets/dir_item.dart
lib/ui/pages/fileviewer/widgets/dir_popup.dart
lib/ui/pages/fileviewer/widgets/path_bar.dart
lib/ui/pages/fileviewer/widgets/sort_sheet.dart
pubspec.lock
pubspec.yaml

refer to: https://github.com/Baseflow/flutter-permission-handler/issues/888#issuecomment-1432174970
Android API level 33 introduced a new storage permission policy: [Granular media permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions).
That means the `READ_EXTERNAL_STORAGE` can not be directly requested when api version >= 33.
We should request one of [READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO), and [READ_MEDIA_AUDIO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_AUDIO) for accessing the app-scoped storage.
In this case, since the …

Fix aos storage permission not be requested when api above 33

---

lib/generated/intl/messages_all.dart
lib/generated/intl/messages_en.dart
lib/generated/l10n.dart
lib/l10n/intl_en.arb
lib/main.dart
lib/ui/pages/score/score_page.dart

This pull request mainly fixes the ripple effect issue in calculation result page, which is described in [this issue](https://github.com/NEO-TAT/tat_flutter/issues/126)
Also did some refactoring and solved some `FIXME`s.
Check the following features:
1. Go to calculation page and long press the `ExpansionTile`s to see if ripple effect covers the entire widget (outside the border).
2. Check if the content in the expansion tile shows as is.

Fix calculation result page background color

---

lib/main.dart
lib/src/controllers/calendar_controller.dart
lib/src/providers/app_provider.dart
lib/src/task/dialog_task.dart
lib/ui/pages/calendar/calendar_page.dart
lib/ui/screen/main_screen.dart

In #154, the new-refactored calendar seems still has some problems.
- The event tile of calendar may be able to scroll overflow, which overlapped the calendar section.
- The event of any day maybe duplicate because the school server can't respond an accurate range of events. For example, if the given event range is 01/01 ~ 01/31, the server may respond events between 12/xx ~ 02/xx (not constantly).
So in this PR, 
- make the event card disappeared when scroll over. (by using the `Card` widget)
- we tried to prevent the event not in expected scope been added into the list while creating calendar.
For the UI problem (prefer validating in iOS):
1. go to calendar page
2. choose a day which contains some events and click it
3. scroll the event list (toward top), check if the overflowed event …

Fix calendar event card scroll overflow

---

lib/ui/other/custom_progress_dialog.dart
lib/ui/other/my_progress_dialog.dart
lib/ui/pages/coursetable/course_table_page.dart

The circular progress indicator in the course table page's appbar seems not pretty enough.
and sometimes it will cause UI overflow exception but not been noticed.
So this PR tried to fix these problems.
Go to course table page, and see the circular progress indicator's color
check if you like it.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/47718989/219870995-09c894d0-b322-4709-b6ba-235378725c63.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/47718989/219870999-b025d82a-1335-47b6-9dbd-4df9c0dc3063.jpg"></td>
</tr>
</table>

Fix circular progress indicator UI

---

lib/main.dart
lib/src/task/ntut/ntut_task.dart
lib/src/task/task_flow.dart

In this PR, we use the `CheckSessionUseCase` in the core package to help us detect where the current session is valid or not.
Sometimes, the client's session will be marked as invalid by server since another client has logged-in, too.
Or it expired by time.
So when we are trying to do other tasks like calendar, iplus, score ..., it will not be able to get an expected response (the step of using real service, 3rd step of ntut login described in core api service interface).
Hence, knowing whether we should start from the step 1, fetch initial JSESSION cookie, is necessary.
And this also solve #62 since it will auto retry.
1. open TAT. this is phone A
2. use another phone, open TAT. this is phone B.
3. go to phone A, and go to calendar page (for `calendar_task`)
4. On phone A, check if it …

Detect whether login session is valid and retry automatically

---

.vscode/settings.json

- This PR adds a configuration file for Visual Studio Code to adhere to rules found in `.github/workflows/analysis.yml`.
- Open the project in Visual Studio Code.
- Invoke `Format Document` command in any Dart file.
- None of the existing code should be modified.
None.

Add VSCode formatter configuration

---

lib/ui/pages/score/score_page.dart

Change the margin of the tabs on the top in score calculation page.
- 
Origin:
Now:

Enhancement #170: Change the tab selected style in score calculation page.

---

lib/ui/screen/login_screen.dart

- This PR causes the username and password fields of the login screen to trigger autofill, improving the UX of password manager users.
- The Column widget gets wrapped with the AutofillGroup widget.
- Prepare an password manager, e.g. KeepassXC2Android or Google Passwords
- Launch the app logged out
- Click on either username or password field triggers the autofill prompt.

Add autofill hints to login screen

---

lib/src/connector/score_connector.dart

A user has a dropout record in the QryRank/QryScore inquiry result, which is not expected in the present data extraction algorithm, so I changed the algorithm and tried to fix this error.
- Test the score connector with the data provided by the user.
- Test with accounts having the same situation and issue.
- Test with normal accounts to validate the correctness of the algorithm.

Rewrite score connecter

---

lib/src/connector/course_connector.dart

See: #203 
Fix the issue by changing the index:
- Note should be 19.
- ScheduleHref should be 18.

Fix: Reload error happened on zh-tw corse information page

---

lib/src/connector/ischool_plus_connector.dart

See: #202 
I-School changed the redirect mechanism and caused the error.
Also see the redirect step: [953570beb7342f34af7385c534f194eeae6e35b5](https://github.com/NEO-TAT/tat_flutter/commit/953570beb7342f34af7385c534f194eeae6e35b5#diff-1f405ce990701e9603e79d66984e588d36aa5637b0719c3980bfc8aa89be66e6R37-R41)

Fix: Loading error since the ISchool change the redirect mechanism

---

lib/src/version/update/app_update.dart

Close: #210 and #175 
在這個 PR 中，我修復了 iPhone12/iOS17 更新跳轉出現異常的問題。
在版本強制更新的 Modal 中，若點擊更新時會導致跳轉出現異常並使應用程式關閉。
在這個版本上我使用 `launchUrl` 與 `LaunchMode` 來取代 `canLaunchUrl`，問題已解決。
> **Warning**
> 由於模擬器並沒有 AppStore，你會需要實體的 iOS 裝置來進行測試。
> **NOTE**
> 你可以安裝 v1.4.5 版本，但請使用 Beta Flavor 進行測試，即 1.4.48763 的假更新消息（但強制更新）。

修復「更新跳轉出現異常」

---

lib/src/connector/ischool_plus_connector.dart
lib/ui/pages/coursedetail/screen/course_info_page.dart

在這個 PR 上修復了誤用 global courseMainInfo 的問題，可能導致以下的 exception 不停觸發。
```
I/flutter (22396): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (22396): NoSuchMethodError: The getter 'course' was called on null.
I/flutter (22396): Receiver: null
I/flutter (22396): Tried calling: course
I/flutter (22396): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter (22396): #1      _CourseInfoPageState._loadCourseStudent (package:flutter_app/ui/pages/coursedetail/screen/course_info_page.dart:232:67)
I/flutter (22396): #2      _CourseInfoPageState.initState.<anonymous closure> (package:flutter_app/ui/pages/coursedetail/screen/course_info_page.dart:48:28)
I/flutter (22396): #3      new Future.microtask.<anonymous closure> (dart:async/future.dart:277:37)
I/flutter …
```

修復「誤用 null courseMainInfo」的問題

---

lib/generated/intl/messages_all.dart
lib/generated/intl/messages_en.dart
lib/generated/intl/messages_zh_TW.dart
lib/generated/l10n.dart
lib/l10n/intl_en.arb
lib/l10n/intl_zh_TW.arb
lib/src/task/iplus/iplus_get_course_student_list_task.dart
lib/ui/pages/coursedetail/screen/course_info_page.dart

在這個 PR 中，我修復了讀取學生列表時出現大量延遲的問題，並且提升了 UI 的流暢度。
目前確定似乎是無意進行了兩次的讀取，並且缺失了讀取學生的 Modal，在這個 PR 上補齊。

修復「讀取學生列表時出現大量延遲」的問題

---

android/app/build.gradle
android/build.gradle

This PR addresses the diffs generated in the Gradle configuration files after building the project. The following updates were applied to ensure compatibility with the build environment:
- Added `ndkVersion` to `android/app/build.gradle`.
- Updated `clean` task syntax in `android/build.gradle` to use `tasks.register` as recommended by newer Gradle versions.
Please follow these steps to review and test the PR:
1. Ensure the project builds successfully after these changes.
2. Validate that the changes to `build.gradle` files persist across builds without generating new diffs.
3. Perform manual testing to verify:
- Compatibility with the specified NDK version.
- Build tasks execute as expected.

chore: apply diffs generated by Flutter 3.7.12 during build

---

lib/ui/pages/other/page/contributors_page.dart

the ListView.builder in the FutureBuilder has no specified height which causes RenderFlex overflowed, so it should be wrapped with a Expanded widget.
Wrapped ListView.builder with a Expanded widget
Please provide details on the steps required to review and test this PR.
build the project and navigate to the contributors page and check if there are overflow error or not

Contributors page render error

---

lib/ui/pages/coursedetail/screen/course_info_page.dart

在這個 PR 中，我回復了修課人數並且新增學生清單標題。
用於顯示目前的修課人數，並且回復學生清單的標題，並在兩個不同的列表中插一個空白來進行區隔。

回復「修課人數」並且新增「學生清單」標題
